Document: tinc-itsyndikat
Title: Debian tinc-itsyndikat Manual
Author: <insert document author here>
Abstract: This manual describes what tinc-itsyndikat is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tinc-itsyndikat/tinc-itsyndikat.sgml.gz

Format: postscript
Files: /usr/share/doc/tinc-itsyndikat/tinc-itsyndikat.ps.gz

Format: text
Files: /usr/share/doc/tinc-itsyndikat/tinc-itsyndikat.text.gz

Format: HTML
Index: /usr/share/doc/tinc-itsyndikat/html/index.html
Files: /usr/share/doc/tinc-itsyndikat/html/*.html
